name: LEAKS
on:
  pull_request:
    branches-ignore:
      - main
    paths-ignore:
      - '.github'
jobs:
  sast_gitleaks:
    permissions:                                                                         
      contents: read
    uses: ramshackle-code/sast_gitleaks/.github/workflows/sast_gitleaks.yml@922631f04aeeee05b0d16295608f13a7616a5844  #v1.3.0
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
