name: LEAKS
on:
  pull_request:
    branches-ignore:
      - main
    paths-ignore:
      - '.github'
jobs:
  sast_gitleaks:
    permissions:                                                                         
      contents: read
    uses: ramshackle-code/sast_gitleaks/.github/workflows/sast_gitleaks.yml@de5a68b4c898df6928e8913759357d5e95a86a6  #v1.3.1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
